chapter12/config/routes.rb
Asagao::Application.routes.draw do
  resources :line_items

  resources :carts
  
  
  

  root to: "top#index"
  get "about" => "top#about", as: "about"

  get "lesson/:action(/:name)" => "lesson"

  resources :members, only: [:index, :show] do
    collection { get "search" }
    
    resources :entries
  end
  resources :entries do
    member { put "like", "unlike" }
    collection { get "voted" }
  end
  
  resources :books do
    collection { get "search" }
  end

  resources :articles, only: [:index, :show]

  resource :session, only: [:create, :destroy]

  namespace :admin do
    root to: "top#index"
    resources :members do
      collection { get "search" }
    end
    resources :books do
      collection { get "search" }
    end
    resources :articles    
  end
  

  resource :account, only: [:show, :edit, :update]

  match "*anything" => "top#not_found"
end

chapter12/app/models/book.rb
class Book < ActiveRecord::Base
  
  
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  
  validates :number, presence: true,
    length: { minimum: 2, maximum: 20, allow_blank: true },
    uniqueness: true
  validates :name, presence: true,
    length: { minimum: 2, maximum: 20, allow_blank: true },
    uniqueness: { case_sensitive: false }
  validates :full_name, length: { maximum: 20 }
  validates :publisher_name, length: { maximum: 20 }
  validates :price, presence: true,
    numericality: { only_integer: true,
       greater_than: 0, less_than: 10000, allow_blank: true }
  validate :place,presence: true,
    length: { minimum: 2, maximum: 20, allow_blank: true }
  validates :kari_name, length: { maximum: 20 }
  validate :kari_email
  validate :kari_place
  
  
  ACCESSIBLE_ATTRS = [ :number, :name , :full_name, :publisher_name, :book_id, 
    :price , :place, :kari_name, :kari_email, :kari_place, :password, :password_confirmation, :image_attributes ]
  attr_accessible *ACCESSIBLE_ATTRS
  attr_accessible *(ACCESSIBLE_ATTRS + [:number, :administrator]),
    as: :admin
  
    def ensure_not_referenced_by_any_line_item
    if line_items.empty?
    return true
    else
    errors.add(:base, 'Line Items present')
    return false
    end
    end
  
  
  class << self
    def search(query)
      rel = order("number")
      if query.present?
        rel = rel.where("name LIKE ? OR full_name LIKE ?",
                "%#{query}%", "%#{query}%")
      end
      rel
    end
  end
end

chapter12/app/controllers/admin/books_controller.rb
# coding: utf-8

class Admin::BooksController < Admin::Base
  # 蔵書一覧
  def index
    @books = Book.order("number")
  end

  # 検索
  def search
    @books = Book.search(params[:q])
    render "index"
  end

  # 蔵書情報の詳細
  def show
    @book = Book.find(params[:id])
  end

  # 新規作成フォーム
  def new
    @book = Book.new()
  end

  # 更新フォーム
  def edit
    @book = Book.find(params[:id])
  end

  # 蔵書の新規登録
  def create
    @book = Book.new(params[:book],as: :admin)
    if @book.save
      redirect_to [:admin, @book], notice: "蔵書を登録しました。"
    else
      render "new"
    end
  end

  # 蔵書情報の更新
  def update
    @book = Book.find(params[:id])
    @book.assign_attributes(params[:book])
    if @book.save
      redirect_to [:admin, @book], notice: "蔵書情報を更新しました。"
    else
      render "edit"
    end
  end

  # 蔵書の削除
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to :admin_books, notice: "蔵書を削除しました。"
  end
end

chapter12/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # 蔵書一覧
  def index
    @books = Book.order("number")
  end

  # 検索
  def search
    @books = Book.search(params[:q])
    render "index"
  end

  # 蔵書情報の詳細
  def show
    @book = Book.find(params[:id])
  end

  # 新規作成フォーム
  def new
    @book = Book.new
  end

  # 更新フォーム
  def edit
    @book = Book.find(params[:id])
  end

  # 蔵書の新規登録
  def create
    @book = Book.new(params[:book])
    if @book.save
      redirect_to @book, notice: "蔵書を登録しました。"
    else
      render "new"
    end
  end

  # 蔵書情報の更新
  def update
    @book = Book.find(params[:id])
    @book.assign_attributes(params[:book])
    if @book.save
      redirect_to @book, notice: "蔵書情報を更新しました。"
    else
      render "edit"
    end
  end

  # 蔵書の削除
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to book, notice: "蔵書を削除しました。"
  end
end

chapter12/app/helpers/books_helper.rb
module BooksHelper
end

chapter12/app/views/books/_body.html.erb
<table class="attr">
  <tr>
    <th width="150">Ibsn番号</th>
    <td><%= @book.number %></td>
  </tr>
  <tr>
    <th>書名</th>
    <td><%= @book.name %></td>
  </tr>
  <tr>
    <th>著作者</th>
    <td><%= @book.full_name %></td>
  </tr>
  <tr>
    <th>出版社</th>
    <td><%= @book.publisher_name %></td>
  </tr>
  <tr>
    <th>価格</th>
    <td><%= @book.price %></td>
  </tr>
  <tr>
    <th>置いた場所</th>
    <td><%= @book.place %></td>
  </tr>
  <tr>
    <th>借り者</th>
    <td><%= @book.kari_name %></td>
  </tr>
  <tr>
    <th>借り者置いた場所</th>
    <td><%= @book.kari_place %></td>
  </tr>
  <tr>
    <th>借り者メール</th>
    <td><%= @book.kari_email %></td>
  </tr>
  
  
</table>

chapter12/app/views/books/index.html.erb
<% @page_title = "蔵書" %>

<h1><%= @page_title %></h1>

<%= form_tag :search_books, method: :get do %>
<p><%= text_field_tag "q", params[:q] %>
<%= submit_tag "検索" %></p>
<% end %>



<% if @books.present? %>
<table class="list">
  <tr>
    <th>本の名前</th>
    <th>著作者</th>
    <th>出版社</th>
    <th>操作</th>
	<th>賃貸</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td align="left"><%= link_to book.name ,book%></td>
    <td><%= book.full_name %></td>
    <td><%= book.publisher_name %></td>
    <td>
      <%= link_to "編集", [:edit, book] %> |
      <%= link_to "削除", book_path(book), method: 'DELETE',
            confirm: 'Are you sure?'  %> </td>
	<td><%= button_to 'Check In', line_items_path(book_id: book)%></td>
  </tr>
  <% end %>
</table>
<% else %>
<p>蔵書情報がありません。</p>
<% end %>

chapter12/app/views/books/show.html.erb
<% @page_title = "蔵書の詳細" %>

<h1><%= @page_title %></h1>

<%= render "body" %>